# Generated by Django 6.0.2 on 2026-03-25 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_category_is_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_parent',
        ),
    ]
