# Generated by Django 6.0.2 on 2026-03-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_remove_category_is_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_parent',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
