# Generated by Django 6.0.2 on 2026-04-21 08:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='budget',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
