# Generated by Django 6.0.2 on 2026-04-03 07:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recurring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringtransaction',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
