# Generated by Django 6.0.2 on 2026-03-25 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_transaction_transaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_type',
        ),
    ]
