# Generated by Django 6.0.2 on 2026-04-30 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recurring', '0002_alter_recurringtransaction_start_date'),
        ('transaction', '0008_alter_transaction_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='recurring_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recurring.recurringtransaction'),
        ),
    ]
