# Generated by Django 6.0.2 on 2026-04-30 13:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_account_balance'),
        ('category', '0005_category_is_parent'),
        ('recurring', '0002_alter_recurringtransaction_start_date'),
        ('transaction', '0009_transaction_recurring_rule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(fields=('recurring_rule', 'transaction_date'), name='unique_recurring_per_day'),
        ),
    ]
