# Generated by Django 6.0.2 on 2026-04-30 13:53

import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_account_balance'),
        ('category', '0005_category_is_parent'),
        ('recurring', '0002_alter_recurringtransaction_start_date'),
        ('transaction', '0010_transaction_unique_recurring_per_day'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='transaction',
            name='unique_recurring_per_day',
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(django.db.models.functions.datetime.TruncDate('transaction_date'), models.F('recurring_rule'), name='unique_recurring_per_day'),
        ),
    ]
